### PR TITLE
:zap: creating GRSP0028

### PR DESCRIPTION
**Pull request by mouradmamassi**
Code To review, I worked just on the read file optimization

### CODE REVIEW

**Comment by dedece35** [comment]
hello @med-S @jules-delecour-dav @glalloue 
 is no review before merging

**Comment by med-S** [comment]
Hello,

We do review twice before merging 🙂

**Comment by dedece35** [comment]
@med-S 
sorry, i didn't wake up well this morning 🤣
i didn't see well that there are two people in this issue 😜

**Comment by med-S** [comment]
Can you please elaborate more on this? Is there any issue that we can
correct ?

**Comment by med-S** [comment]
Lol it’s ok
However, thanks for the comment

**Pull request merged**
