### PR TITLE
[Rule-S75] Java Rule: Avoid Strings concatenation

### PR DESCRIPTION
**Pull request by FunixG**
The goal of this rule is made to avoid Strings concatenation. Strings are immutable so each time you concatenate a String, a new String is created. This is a waste of memory and CPU.

image

### CODE REVIEW

**Comment by olegoaer** [comment]
hi,
Do you check that the string concatenation occurs in a loop, and moreover in a "big" loop?
Otherwise, the severity of this rule is minor.

**Comment by FunixG** [comment]
> hi, Do you check that the string concatenation occurs in a loop, and moreover in a "big" loop? Otherwise, the severity of this rule is minor.

Hello !
I am actually refactoring my rule, I have read that this rules does not apply to all loops, and what do you mean by big loop ? Do you have an example ? :D

Thanks for the feedback I will change the rule severity.

**Comment by FunixG** [comment]
This PR is ready to review !
PS : I am working on this project thanks to @jules-delecour-dav who talked about that in a module at @Epitech

**Comment by olegoaer** [comment]
> 

My question deliberately focuses on this point. It is almost impossible to define what is a big loop (ex: more than 10000 iterations) in static analysis. Yet it is said that the concatenation problem only appears in big loops ;)

**Comment by FunixG** [comment]
> > 
> 
> My question deliberately focuses on this point. It is almost impossible to define what is a big loop (ex: more than 10000 iterations) in static analysis. Yet it is said that the concatenation problem only appears in big loops ;)

Ok I see ! There is someting in sonarqube where you can set an issue as "False Positive" the user can check if this rule is useful for him or not. Is this relevant ? Or this rule is too precise to be implemented ?

**Comment by MP-Aubay** [comment]
Hi,

This rule already exist in Sonarqube : https://rules.sonarsource.com/java/type/Code%20Smell/RSPEC-1643 

Wondering how to handle this case, the rule is simply a "code smell" in Sonarqube but it's a little more in EcoCode point of view.

Regards,
Mikaël

**Comment by olegoaer** [comment]
> 
Broadly speaking, this kind of code smell falls into the _performance_ category. I recall that the innovation behind ecoCode is to address a separate concern: the carbon footprint (not necessarily related to performance). It is important to keep this in mind IMHO.

**Pull request merged**
