### PR TITLE
Add ecolinter plugin

### PR DESCRIPTION
**Pull request by nduheron**
🍺

### CODE REVIEW

**Comment by bosseludovic** [comment]
Unit tests are coded and Jacoco has been added on my local branch but it seems like we don't have the rights to push anymore. Maybe because the eco challenge is over? Let me know if I'm wrong and if I can push the unit tests.

**Comment by bosseludovic** [comment]
Unit tests have been added but they seem not to be viewed by Sonar.

**Comment by dedece35** [comment]
Hi,

I'm not expert in front frameworks but after reviewing your code I have some questions : 
- why do you use "ecolinter" name for your plugin ? because in the futur, we would like tocreate a linter for another language different of JS or CSS :p
- sometimes you use "ecolinter" and sometimes "eslint" in your code. for me, is not homogeneous. and why do you use "es" in "eslint" word ? for "EcmaScript" ?
- I think the name of plugin is too much general. It deals with JS and CSS, why not "jscss-plugin" ?
- do you check if your implemented rules are not already present in SonarQube natively ? and thus, if yes, adding `eco-conception` tag is sufficient, no ?

**Comment by bosseludovic** [comment]
Hi,
First of all, sorry but I just merged the PR without noticing your comment. I'll try to answer you:

- why do you use "ecolinter" name for your plugin ? because in the futur, we would like tocreate a linter for another language different of JS or CSS :p
- > The aim of this plugin is to add some descriptions of code smell in Sonar, not regarding the language. Until now we just add EsLint and StyleLint but you could add any other "repository".

- sometimes you use "ecolinter" and sometimes "eslint" in your code. for me, is not homogeneous. and why do you use "es" in "eslint" word ? for "EcmaScript" ?
- > Es indeed stands for EcmaScript (https://eslint.org/). EsLint is just one of the repository already added to this plugin.

I think the name of plugin is too much general. It deals with JS and CSS, why not "jscss-plugin" ?
do you check if your implemented rules are not already present in SonarQube natively ? and thus, if yes, adding eco-conception tag is sufficient, no ?
-> As explained just before, the plugin is not only for JS or CSS but for any language as you wish.

**Comment by MP-Aubay** [comment]
Hi @bosseludovic 

I do not understand how this plugin works.

It seems linked to this linter https://github.com/cnumr/ecoLinter, the goal is to use this linter during Sonarqube analysis ? 

I can see docs refering to the linter, but I can not see how rules are applied (if they are).

@dedece35 : To add more context, the Javascript Sonar plugin (as we do it for java, php, ...) is deprecated (or already dead) and the recommandation is to use linter to check Javascript code.

**Comment by MP-Aubay** [comment]
Hi @bosseludovic,

Thank you for the explanation :) So this plugin is "only" for documenting rules, I think a little README could be usefull in `src/ecolinter-plugin` to explain that and the link to ecoLinter repo.

**Pull request merged**
